{% set name = "django-nose" %}
{% set version = "1.4.5" %}
{% set sha256 = "87663f18cb25f01d56c84ac1ff8a0e6e6a6246264b2549b751cb239d0642e76a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - django >=1.8
    - nose >=1.2.1

test:
  imports:
    - django_nose
    - django_nose.management
    - django_nose.management.commands

about:
  home: http://github.com/django-nose/django-nose
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Makes your Django tests simple and snappy'

  dev_url: http://github.com/django-nose/django-nose
  doc_url: https://django-nose.readthedocs.io/

extra:
  recipe-maintainers:
    - sodre
